# Generated by Django 5.1.7 on 2025-05-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_accesstype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstype',
            name='name',
            field=models.CharField(choices=[('private', 'Private'), ('readonly', 'Read-Only'), ('write', 'Writable')], max_length=20, unique=True),
        ),
    ]
