# Generated by Django 5.1.7 on 2025-05-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_lesson_created_lesson_updated_word_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
