# Generated by Django 5.1.7 on 2025-05-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_lesson_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlesson',
            name='target_progress',
            field=models.IntegerField(default=3),
        ),
    ]
