# Generated by Django 5.1.7 on 2025-05-23 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_lesson_alter_message_options_word_userlesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='prompt_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_lessons', to='base.language'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='translation_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_lessons', to='base.language'),
        ),
    ]
