# Generated by Django 5.1.7 on 2025-05-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='changes_log',
            field=models.TextField(blank=True, help_text='Log of changes made to this lesson.'),
        ),
    ]
