# Generated by Django 5.1.7 on 2025-05-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_room_host_remove_room_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlesson',
            name='lesson_directory',
            field=models.CharField(blank=True, help_text='Directory where the lesson is stored.', max_length=255),
        ),
    ]
