# Generated by Django 5.1.7 on 2025-05-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_userlesson_lesson_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlesson',
            name='lesson_directory',
        ),
    ]
