# Generated by Django 5.1.7 on 2025-05-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_userlesson_lesson_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlesson',
            name='practice_window',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
