# Generated by Django 5.1.7 on 2025-05-29 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_userlesson_practice_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlesson',
            name='practice_window',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='target_progress',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
