# Generated by Django 5.1.7 on 2025-05-29 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_lesson_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlesson',
            name='allowed_error_margin',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
