# Generated by Django 5.1.7 on 2025-05-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_userlesson_allowed_error_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='prompt_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/prompts/'),
        ),
        migrations.AddField(
            model_name='word',
            name='usage_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/usages/'),
        ),
    ]
