# Generated by Django 5.1.7 on 2026-02-03 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_userprofile_allowed_error_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='target_progress',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
