# Generated by Django 5.1.7 on 2026-02-03 16:40

from django.db import migrations


def create_root_directories_for_existing_users(apps, schema_editor):
    """Create root directories for all existing users and assign orphan lessons to root."""
    User = apps.get_model('auth', 'User')
    UserDirectory = apps.get_model('base', 'UserDirectory')
    UserLesson = apps.get_model('base', 'UserLesson')
    
    for user in User.objects.all():
        # Create root directory if it doesn't exist
        root_dir, created = UserDirectory.objects.get_or_create(
            user=user,
            is_root=True,
            defaults={'name': 'Home', 'parent_directory': None}
        )
        
        # Move all orphan lessons (without directory) to root
        UserLesson.objects.filter(user=user, directory__isnull=True).update(directory=root_dir)


def reverse_migration(apps, schema_editor):
    """Remove root directories and set lessons' directory to null."""
    UserDirectory = apps.get_model('base', 'UserDirectory')
    UserLesson = apps.get_model('base', 'UserLesson')
    
    # Set all lessons' directory to null
    UserLesson.objects.all().update(directory=None)
    
    # Delete all root directories
    UserDirectory.objects.filter(is_root=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_userdirectory_userlesson_directory'),
    ]

    operations = [
        migrations.RunPython(create_root_directories_for_existing_users, reverse_migration),
    ]
