# Generated by Django 5.1.7 on 2026-02-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_create_root_directories_for_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_generate_hints',
            field=models.BooleanField(default=True),
        ),
    ]
